name: Flutter Build Action
run-name:  Building Flutter App
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Flutter-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.8.0
          cache: true
      - run: flutter pub get
      - run: flutter build apk
      - name: upload artifects
        uses: actions/upload-artifact@master
        with:
          name: android-app
          path: build/app/outputs/apk/release
      - uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          args: 'build/app/outputs/apk/release/app-release.apk'

