name: Flutter Build Action
run-name:  Building Flutter App
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Flutter-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.8.0
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

